FROM rockylinux:8

COPY bootstrap-prefix.sh /usr/local/bin/bootstrap-prefix.sh

RUN dnf install -y gcc gcc-c++ make diffutils gmp-devel perl
RUN dnf install -y git python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install ansible
RUN chmod 755 /usr/local/bin/bootstrap-prefix.sh

ENV LC_ALL=C
ENV PATH=/usr/local/bin:$PATH

RUN groupadd -g 1000 portage && useradd -ms /bin/bash -u 1000 -g portage portage

ENTRYPOINT ["/usr/local/bin/bootstrap-prefix.sh"]
