# Add a custom overlay to the Gentoo Prefix installation.
---
- name: Install equery command (dependency for the portage module)
  ansible.builtin.command:
    cmd: emerge gentoolkit
    creates: "{{ gentoo_prefix_path }}/usr/bin/equery"

# We need git in order to add Gentoo overlays hosted on git repositories.
- name: Install git
  community.general.portage:
    package: dev-vcs/git
    state: present

- name: Add configuration files for custom overlays
  ansible.builtin.template:
    src: overlay.conf.j2
    dest: "{{ gentoo_prefix_path }}/etc/portage/repos.conf/{{ item.name }}.conf"
    mode: "0644"
  loop: "{{ custom_overlays }}"

- name: Make configuration file with overlays that can override eclasses
  ansible.builtin.copy:
    dest: "{{ gentoo_prefix_path }}/etc/portage/repos.conf/eclass-overrides.conf"
    mode: "0644"
    content: |
      [DEFAULT]
      eclass-overrides = {{
        custom_overlays | selectattr('eclass-overrides', 'defined') |
        selectattr('eclass-overrides', 'equalto', True) | map(attribute='name') | join(' ')
      }}

- name: "Import the task for checking out the specific commit of git-based overlays"
  ansible.builtin.include_tasks: sync_git_overlay.yml
  vars:
    gitrepo: "{{ item }}"
  # also include the Gentoo git repo here in case we want to switch to a different commit
  loop: >-
    {{
      custom_overlays | selectattr('source', 'equalto', 'git') +
      [{'name': 'gentoo', 'url': gentoo_git_repo, 'branch': gentoo_git_branch, 'commit': gentoo_git_commit}]
    }}

# We do an explicit sync here (instead of using a handler),
# so we can be sure that non-git overlays are also up-to-date.
- name: Sync overlays with auto-sync enabled to make sure that they are up to date
  community.general.portage:
    sync: 'yes'
    verbose: true
...
