# Replace a list of files/directories in Gentoo Prefix installation by (variant) symlinks to corresponding files/directories
# on the host in order to solve some common issues.
---

- name: Check type of original files/directories
  ansible.builtin.stat:
    path: "{{ item.dest if item is mapping else gentoo_prefix_path + item }}"
  with_items: "{{ symlinks_to_host }}"
  register: orig_types

- name: Remove original files/directories
  ansible.builtin.file:
    path: "{{ item.item.dest if item is mapping else gentoo_prefix_path + item.item }}"
    state: absent
  with_items: "{{ orig_types.results }}"
  when:
    - item.stat.exists
    - not item.stat.islnk

- name: Make symlinks
  ansible.builtin.file:
    # Variant symlink destinations look like: $(EESSI_COMPAT_ETC_HOSTS):-/etc/hosts
    # So, if we don't want to use variant symlinks, we cut off the part after :-
    src: "{{ symlink_src if (use_variant_symlinks | default(true)) else (symlink_src | split(':-') | last) }}"
    dest: "{{ symlink_dest }}"
    state: link
    force: true
  vars:
    # If the list item is a string, the symlink is assumed to be like /dir/file -> $EPREFIX/dir/file.
    # Otherwise, it should have a src and dest attribute and we use that.
    symlink_dest: "{{ item.dest if item is mapping else gentoo_prefix_path + item }}"
    symlink_src: "{{ item.src if item is mapping else item }}"
  with_items: "{{ symlinks_to_host }}"
