# Install a specified list of sets and packages.
---
- name: Install package sets
  community.general.portage:
    package: "@{{ item }}"
    state: present
  with_items: "{{ package_sets }}"
  tags:
    - set

- name: Determine packages to be installed for this architecture
  ansible.builtin.set_fact:
    # Join the following subsets of items from the package list:
    #   - packages without architecture constraints
    #   - packages with a "include_on" constraint that includes this architecture
    #   - packages with a "exclude_on" constraint that don't include this architecture
    eessi_os_arch_packages: |
      prefix_packages
        | rejectattr('include_on', 'defined')
        | rejectattr('exclude_on', 'defined')
      + prefix_packages
        | selectattr('include_on', 'defined')
        | selectattr('include_on', 'contains', eessi_host_os + '-' + eessi_host_arch)
      + prefix_packages
        | rejectattr('include_on', 'defined')
        | selectattr('exclude_on', 'defined')
        | rejectattr('exclude_on', 'contains', eessi_host_os + '-' + eessi_host_arch)

- name: Install EESSI packages
  community.general.portage:
    # Construct package atom:
    #   category/name
    #   =category/name-version
    #   =category/name-version::overlay
    package: "{{ '=' if item.version is defined }}{{ item.name }}{{ '-' + item.version if item.version is defined }}{{ '::' + item.overlay if item.overlay is defined }}"
    state: present
  loop: "{{ eessi_os_arch_packages }}"
