# Defaults file for the compatibility layer role.
---
eessi_version: "2026.06"
eessi_host_os: "linux"
eessi_host_arch: "x86_64"

custom_overlays:
  - name: eessi
    source: git
    url: https://github.com/EESSI/gentoo-overlay.git
    eclass-overrides: true

cvmfs_repository: software.eessi.io

gentoo_prefix_path: /cvmfs/{{ cvmfs_repository }}/versions/{{ eessi_version }}/compat/{{ eessi_host_os }}/{{ eessi_host_arch }}

# How to build the prefix.
gentoo_git_repo: https://github.com/gentoo/gentoo.git
gentoo_git_branch: master
prefix_required_space: 15 GB
prefix_user_defined_trusted_dirs: []
prefix_accept_keywords:
prefix_make_conf_files:
prefix_package_env_files:
    package.env: |
        dev-util/direnv test.conf
        sys-apps/archspec test.conf
        sys-cluster/lmod test.conf
        sys-cluster/reframe test.conf
    env/test.conf: |
        FEATURES="test"
    env/sys-libs/glibc: |
        # Don't use RPATH for glibc itself
        LDFLAGS="$(echo \"${LDFLAGS}\" | sed 's|-Wl,-rpath,[^ ]*||g' | sed 's|-Wl,--disable-new-dtags||g')"

prefix_profile_package_use_mask:
    # unmask the pam USE flag for nss-pam-ldapd and sssd
    sys-auth/nss-pam-ldapd -pam
    sys-auth/sssd -pam
prefix_mask_packages:
prefix_unmask_packages:
prefix_bootstrap_use_flags:
prefix_use_builtin_bootstrap: false
prefix_custom_bootstrap_script:
  local: "{{ playbook_dir }}/../../bootstrap-prefix.sh"
  remote: /tmp/bootstrap-prefix.sh
prefix_source_options: "{{ gentoo_prefix_path }} noninteractive"
prefix_install: >-
    {{ prefix_use_builtin_bootstrap | ternary('/usr/local/bin/bootstrap-prefix.sh', prefix_custom_bootstrap_script.remote) }}
    {{ prefix_source_options }}

# Reproducibility settings
prefix_reprod_dir: reprod
prefix_packages_file: packages.txt
prefix_metadata_json: build.json

# Logging
eessi_log_dir: "/tmp/eessi-logs"
prefix_build_log: "{{ eessi_log_dir }}/prefix-build.log"
emerge_log: "{{ gentoo_prefix_path }}/var/log/emerge.log"

prefix_locales:
  - en_US.UTF-8 UTF-8

# By default, we install an architecture-specific set
package_sets:
  - "eessi-{{ eessi_version }}-{{ eessi_host_os }}-{{ eessi_host_arch }}"

prefix_packages: []
prefix_remove_packages: []

reframe_venv_dir: /tmp/reframe_venv

# List of locations that should get a symlink $EPREFIX/$LOCATION -> $LOCATION.
# This ensures that things like user/group ids are correct/looked up in the right way in the Prefix environment.
symlinks_to_host: []
