name: Ansible Lint

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  ansible-lint:

    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Lint Ansible Playbook
        # replace "master" with any valid ref
        uses: ansible/ansible-lint@4114ad63edbc25dcd9afc4f41b29dbcbebdf21ca # v25.5.0
        with:
          args: ""
